# EMBEDDED SERVER CONFIGURATION
server:
  context-path: /keemono

spring:
  jpa:
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://46.4.112.248:10001/keemonotest?UseUnicode=true&amp;characterEncoding=utf8&amp;default_schema=true
    username: keemono
    password: keemono

cerberus:
  token:
    header: api_key
    secret: sssshhhh!
    expiration: 6500
  route:
    authentication: auth
    refresh: refresh
    protected: protected

documentation:
  services:
    basePath: http://localhost:8080/keemono
    version: 1.0

hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  hbm2ddl:
    auto: validate
  ejb:
    naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
  show_sql: false
  format_sql: true

logging:
  level:
    root: ERROR
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type: INFO

mysql:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://46.4.112.248:10001/keemonotest?UseUnicode=true&amp;characterEncoding=utf8&amp;default_schema=true
  user: keemono
  passwd: keemono

dataSource:
  url: jdbc:mysql://46.4.112.248:10001/keemonotest?UseUnicode=true&amp;characterEncoding=utf8&amp;default_schema=true
  user: keemono
  password: keemono
  ndbBatchSize: 100



