ALTER TABLE `page` CHANGE COLUMN `uuid` `uuid` VARCHAR(45) NOT NULL ;
ALTER TABLE `layout` CHANGE COLUMN `uuid` `uuid` VARCHAR(45) NOT NULL ;
ALTER TABLE `user` CHANGE COLUMN `uuid` `uuid` VARCHAR(45) NOT NULL ;